export const settingsStorageKeys = {
  gameMode: "chess-coach.game-mode",
  playerSide: "chess-coach.player-side",
  botLevelId: "chess-coach.bot-level-id",
  compactUi: "chess-coach.compact-ui",
  showAnalysisArrows: "chess-coach.show-analysis-arrows",
  boardTheme: "chess-coach.board-theme",
  entitlement: "chess-coach.entitlement",
  subscriptionTier: "chess-coach.subscription-tier",
  privacyConsent: "chess-coach.privacy-consent",
  activeWorkspace: "chess-coach.active-workspace",
  trainingBestStreak: "chess-coach.training-best-streak",
  trainingTotalAttempts: "chess-coach.training-total-attempts",
  trainingTotalSuccesses: "chess-coach.training-total-successes",
  trainingDailyDate: "chess-coach.training-daily-date",
  trainingDailySuccesses: "chess-coach.training-daily-successes",
  trainingReviewQueue: "chess-coach.training-review-queue",
  aiCoachUsage: "chess-coach.ai-coach-usage",
  chessAchievements: "chess-coach.chess-achievements",
  onboarding: "chess-coach.onboarding",
} as const;

export const gameSessionStorageKeys = {
  currentPgn: "chess-coach.current-pgn",
  botGameStarted: "chess-coach.bot-game-started",
  gameTermination: "chess-coach.game-termination",
  gameArchive: "chess-coach.game-archive",
  reviewAnalysisCache: "chess-coach.review-analysis-cache",
  reviewCheckpoint: "chess-coach.review-checkpoint",
} as const;
